name: Daily AI Business Briefing

on:
  schedule:
    - cron: '30 3 * * *'          # 05:30 CEST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:                          # nur noch benötigte Secrets
      OPENAI_API_KEY:           ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_DRIVE_FOLDER:      ${{ secrets.GOOGLE_DRIVE_FOLDER }}

    steps:
    # ───────────────────────── Code holen
    - name: Checkout repository
      uses: actions/checkout@v4

    # ───────────────────────── Python 3.11
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # ───────────────────────── Pakete
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install google-cloud-texttospeech>=2.16.1
        pip install -r requirements.txt      # feedparser, requests, openai …

    # ───────────────────────── SA-Key anlegen & ADC setzen
    - name: Write SA key & set ADC
      run: |
        echo '${{ secrets.GDRIVE_CREDENTIALS_B64 }}' | base64 -d > /tmp/sa.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa.json" >> $GITHUB_ENV

    # ───────────────────────── Workflow-Logik
    - name: Crawl & score news
      run: python crawl.py

    - name: Build podcast script
      run: python summarize.py

    - name: Generate MP3 with Google Cloud TTS
      run: python tts.py                     # erzeugt output/YYYY-MM-DD_briefing.mp3

    # ───────────────────────── Datei hochladen
    - name: Upload MP3 to Google Drive
      uses: willo32/google-drive-upload-action@v1
      with:
        target:           output/*.mp3
        credentials:      ${{ secrets.GDRIVE_CREDENTIALS_B64 }}
        parent_folder_id: ${{ env.GOOGLE_DRIVE_FOLDER }}
