name: Daily AI Business Briefing

on:
  schedule:
    - cron: '30 3 * * *'      # 05:30 CEST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY:  ${{ secrets.GEMINI_API_KEY }}
      OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install & pin dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # ↓↓↓  HIER war der Fehler: Block mit | einleiten  ↓↓↓
      - name: Show google-generativeai version
        run: |
          python - <<'PY'
          import importlib.metadata, sys
          print(
              "google-generativeai version:",
              importlib.metadata.version("google-generativeai")
          )
          PY

      - name: Crawl & score news
        run: python crawl.py

      - name: Build podcast script
        run: python summarize.py

      - name: Generate MP3 with Gemini TTS
        run: python tts.py

      - name: Upload MP3 to Google Drive
        uses: willo32/google-drive-upload-action@v1
        with:
          target:           output/*.mp3
          credentials:      ${{ secrets.GDRIVE_CREDENTIALS }}
          parent_folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER }}
