name: Daily AI Business Briefing

on:
  # 05:30 CEST entspricht 03:30 UTC
  schedule:
    - cron: '30 3 * * *'
  # manueller Start in GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # ▸ Secrets als Umgebungs­variablen für alle Steps
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crawl & score news
        run: python crawl.py

      - name: Build podcast script
        run: python summarize.py

      - name: Generate MP3 with Gemini TTS
        run: python tts.py            # legt output/YYYY-MM-DD_briefing.mp3 an

      - name: Upload MP3 to Google Drive
        uses: willo32/google-drive-upload-action@v1
        with:
          target: output/*.mp3                         # Datumsteil variiert täglich
          parent_folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER }}
          credentials:      ${{ secrets.GDRIVE_CREDENTIALS }}
