name: Daily AI Business Briefing

on:
  schedule:
    - cron: '30 3 * * *'               # 05 : 30 CEST – Zeit nach Bedarf anpassen
  workflow_dispatch:                   # manueller Start möglich

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    # ─────────────────────────────────────────────────────────────
    - name: Checkout repository
      uses: actions/checkout@v4

    # ─────────────────────────────────────────────────────────────
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # ─────────────────────────────────────────────────────────────
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install google-cloud-texttospeech>=2.16.1
        pip install -r requirements.txt        # feedparser, requests, openai …

    # ─────────────────────────────────────────────────────────────
    #  Service-Account-Key als Datei ablegen und ADC setzen
    - name: Write SA key & set ADC
      run: |
        echo '${{ secrets.GDRIVE_CREDENTIALS }}' > /tmp/sa.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa.json" >> $GITHUB_ENV
