name: Daily AI Business Briefing
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_DRIVE_FOLDER:   ${{ secrets.GOOGLE_DRIVE_FOLDER }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: '3.11' }

    - name: Install deps
      run: |
        pip install --upgrade pip
        pip install google-cloud-texttospeech>=2.16.1
        pip install -r requirements.txt

    - name: ADC write
      run: |
        echo '${{ secrets.GDRIVE_CREDENTIALS_B64 }}' | base64 -d > /tmp/sa.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa.json" >> $GITHUB_ENV

    # ------------------- dein Workflow -------------------
    - run: python crawl.py
      name: Crawl & score news

    - run: python summarize.py
      name: Build podcast script

    - run: python tts.py
      name: Generate MP3 with Google Cloud TTS            # erzeugt output/YYYY-MM-DD_briefing.mp3

    # ---------- Datei in einen festen Namen kopieren -----
    - name: Statically name MP3
      run: |
        cp output/*.mp3 briefing.mp3
        echo "Briefing file: $(ls -l briefing.mp3)"

    # ------------------ Upload nach Drive ----------------
    - name: Upload MP3 to Google Drive
      uses: willo32/google-drive-upload-action@v1
      with:
        target: briefing.mp3                              # ← fester Dateiname
        credentials: ${{ secrets.GDRIVE_CREDENTIALS_B64 }}
        parent_folder_id: ${{ env.GOOGLE_DRIVE_FOLDER }}
